
[tool.ruff]
line-length = 88
target-version = "py310"
fix = true

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D203", "D212", "ANN101", "ANN102", "FBT003"]  # игнорируем спорные правила

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"

[tool.uv]
dev-dependencies = ["ruff"]
